CREATE TABLE users (
    id UUID NOT NULL,
    email VARCHAR(255),
    username VARCHAR(255) NOT NULL,
    avatar VARCHAR(255),
    register_time TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT users_pk PRIMARY KEY (id),
    CONSTRAINT users_email_unique UNIQUE (email)
);

CREATE TABLE user_auth (
    id UUID NOT NULL,
    user_uuid UUID NOT NULL,
    auth_type VARCHAR(255) NOT NULL,
    identifier VARCHAR(255) NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT user_auth_pk PRIMARY KEY (id)
);

CREATE TABLE api_key (
    id UUID NOT NULL,
    user_id UUID NOT NULL,
    key VARCHAR(255) NOT NULL,
    created_time TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT api_key_pk PRIMARY KEY (id)
);

CREATE TABLE project (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    user_uuid UUID NOT NULL,
    name VARCHAR(255) NOT NULL,
    description VARCHAR(255),
    strategy VARCHAR(255),
    avg_duration INTEGER NOT NULL DEFAULT 0,
    cost NUMERIC(38, 6) NOT NULL DEFAULT 0,
    created_timestamp TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_update_timestamp TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT project_pk PRIMARY KEY (id)
);

CREATE TABLE trace (
    id UUID NOT NULL,
    parent_trace_id UUID,
    project_name VARCHAR(255) NOT NULL,
    project_id BIGINT NOT NULL,
    name VARCHAR(255) NOT NULL,
    conversation_id UUID NOT NULL,
    tags JSONB NOT NULL DEFAULT '[]'::JSONB,
    input JSONB,
    output JSONB,
    error_info VARCHAR(255),
    start_time TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_update_timestamp TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT trace_pk PRIMARY KEY (id)
);

CREATE INDEX idx_trace_parent ON trace(parent_trace_id);

CREATE TABLE step (
    id UUID NOT NULL,
    name VARCHAR(255) NOT NULL,
    trace_id UUID NOT NULL,
    parent_step_id UUID,
    type VARCHAR(255) NOT NULL,
    tags JSONB NOT NULL DEFAULT '[]'::JSONB,
    input JSONB,
    output JSONB,
    error_info VARCHAR(255),
    model VARCHAR(255),
    usage JSONB,
    project_name VARCHAR(255) NOT NULL,
    project_id BIGINT NOT NULL,
    start_time TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    end_time TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT step_pk PRIMARY KEY (id)
);

CREATE TABLE step_meta (
    id UUID NOT NULL,
    metadata JSONB NOT NULL,
    cost NUMERIC(10, 6) NOT NULL DEFAULT 0,
    CONSTRAINT step_meta_pk PRIMARY KEY (id)
);

CREATE TABLE media_asset (
    id UUID NOT NULL,
    project_id BIGINT NOT NULL,
    user_id UUID NOT NULL,
    storage_key VARCHAR(512) NOT NULL,
    mime_type VARCHAR(128) NOT NULL,
    size_bytes BIGINT NOT NULL,
    created_time TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT media_asset_pk PRIMARY KEY (id)
);
