/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --env-interface=CloudflareBindings` (hash: 55e9587f1677b702ae9fd84d1d6574a1)
interface __BaseEnv_CloudflareBindings {
	DB: D1Database;
	OSS_ENDPOINT: "oss-cn-shanghai.aliyuncs.com";
	OSS_BUCKET: "mwintrack";
	OSS_MAX_RAW_SIZE_BYTES: "8388608";
	OSS_MAX_STORED_SIZE_BYTES: "8388608";
	TELEMETRY_MAX_REQUEST_SIZE_BYTES: "16777216";
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_CloudflareBindings {}
}
interface CloudflareBindings extends __BaseEnv_CloudflareBindings {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "OSS_ENDPOINT" | "OSS_BUCKET" | "OSS_MAX_RAW_SIZE_BYTES" | "OSS_MAX_STORED_SIZE_BYTES" | "TELEMETRY_MAX_REQUEST_SIZE_BYTES">> {}
}
