package com.supertrace.aitrace.domain.core.usage;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.PropertyNamingStrategies;
import com.fasterxml.jackson.databind.annotation.JsonNaming;
import lombok.Data;

/**
 * OpenAI usage implementation.
 * Compatible with OpenAI Chat Completions API, Responses API, Audio/Voice API, and Realtime API.
 *
 * @see <a href="https://platform.openai.com/docs/api-reference/chat">Chat Completions API</a>
 * @see <a href="https://platform.openai.com/docs/api-reference/responses">Responses API</a>
 */
@JsonNaming(PropertyNamingStrategies.SnakeCaseStrategy.class)
@Data
public class OpenAIUsage implements LLMUsage {
    /**
     * Number of tokens in the prompt.
     */
    private Integer promptTokens;

    /**
     * Number of tokens in the generated completion.
     */
    private Integer completionTokens;

    /**
     * Total tokens used in the request (prompt + completion).
     */
    private Integer totalTokens;

    /**
     * Breakdown of tokens used in the prompt.
     */
    private PromptTokensDetails promptTokensDetails;

    /**
     * Breakdown of tokens used in a completion.
     */
    private CompletionTokensDetails completionTokensDetails;

    @Override
    public Integer getAudioTokens() {
        // Sum of audio tokens from both prompt and completion
        int audio = 0;
        if (promptTokensDetails != null && promptTokensDetails.getAudioTokens() != null) {
            audio += promptTokensDetails.getAudioTokens();
        }
        if (completionTokensDetails != null && completionTokensDetails.getAudioTokens() != null) {
            audio += completionTokensDetails.getAudioTokens();
        }
        return audio > 0 ? audio : null;
    }

    @Override
    public Double getCost() {
        // OpenAI doesn't provide cost directly in response
        // This can be calculated based on model pricing if needed
        return null;
    }

    /**
     * Details about tokens used in the prompt.
     */
    @JsonNaming(PropertyNamingStrategies.SnakeCaseStrategy.class)
    @Data
    public static class PromptTokensDetails {
        /**
         * Number of tokens that were cached and reused from a previous request.
         */
        private Integer cachedTokens;

        /**
         * Number of audio input tokens present in the prompt.
         */
        private Integer audioTokens;
    }

    /**
     * Details about tokens used in the completion.
     */
    @JsonNaming(PropertyNamingStrategies.SnakeCaseStrategy.class)
    @Data
    public static class CompletionTokensDetails {
        /**
         * Number of tokens generated by the model for reasoning (e.g., o1 model reasoning tokens).
         */
        private Integer reasoningTokens;

        /**
         * Number of audio output tokens generated by the model.
         */
        private Integer audioTokens;

        /**
         * Number of tokens in the prediction that appeared in the completion (Predicted Outputs feature).
         */
        private Integer acceptedPredictionTokens;

        /**
         * Number of tokens in the prediction that did not appear in the completion (Predicted Outputs feature).
         */
        private Integer rejectedPredictionTokens;
    }
}
