package com.supertrace.aitrace.domain.core.usage;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.PropertyNamingStrategies;
import com.fasterxml.jackson.databind.annotation.JsonNaming;
import lombok.Data;

/**
 * OpenRouter usage implementation.
 * Includes cost tracking and detailed token information.
 *
 * @see <a href="https://openrouter.ai/docs/guides/guides/usage-accounting">OpenRouter Usage Accounting</a>
 */
@JsonNaming(PropertyNamingStrategies.SnakeCaseStrategy.class)
@Data
public class OpenRouterUsage implements LLMUsage {
    /**
     * Number of tokens in the prompt.
     */
    private Integer promptTokens;

    /**
     * Number of tokens in the generated completion.
     */
    private Integer completionTokens;

    /**
     * Total tokens used in the request (prompt + completion).
     */
    private Integer totalTokens;

    /**
     * Cost in credits for this API call.
     */
    private Double cost;

    /**
     * Breakdown of tokens used in the prompt.
     */
    private PromptTokensDetails promptTokensDetails;

    /**
     * Breakdown of tokens used in the completion.
     */
    private CompletionTokensDetails completionTokensDetails;

    /**
     * Additional cost details specific to OpenRouter.
     */
    private CostDetails costDetails;

    @Override
    public Integer getAudioTokens() {
        // Sum of audio tokens from both prompt and completion
        int audio = 0;
        if (promptTokensDetails != null && promptTokensDetails.getAudioTokens() != null) {
            audio += promptTokensDetails.getAudioTokens();
        }
        if (completionTokensDetails != null && completionTokensDetails.getAudioTokens() != null) {
            audio += completionTokensDetails.getAudioTokens();
        }
        return audio > 0 ? audio : null;
    }

    /**
     * Details about tokens used in the prompt.
     */
    @JsonNaming(PropertyNamingStrategies.SnakeCaseStrategy.class)
    @Data
    public static class PromptTokensDetails {
        /**
         * Number of tokens that were cached and reused from a previous request.
         */
        private Integer cachedTokens;

        /**
         * Number of audio input tokens present in the prompt.
         */
        private Integer audioTokens;

        /**
         * Number of tokens that were written to the cache.
         * Only returned for models with explicit caching and cache write pricing.
         */
        private Integer cacheWriteTokens;
    }

    /**
     * Details about tokens used in the completion.
     */
    @Data
    public static class CompletionTokensDetails {
        /**
         * Number of tokens generated by the model for reasoning.
         */
        private Integer reasoningTokens;

        /**
         * Number of audio output tokens generated by the model.
         */
        private Integer audioTokens;

        /**
         * Number of tokens in the prediction that appeared in the completion.
         */
        private Integer acceptedPredictionTokens;

        /**
         * Number of tokens in the prediction that did not appear in the completion.
         */
        private Integer rejectedPredictionTokens;
    }

    /**
     * Details about costs incurred for this request.
     */
    @JsonNaming(PropertyNamingStrategies.SnakeCaseStrategy.class)
    @Data
    public static class CostDetails {
        /**
         * Cost from the upstream provider (only for BYOK - Bring Your Own Key requests).
         */
        private Double upstreamInferenceCost;
    }
}
